version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-smarthouse
    environment:
      POSTGRES_DB: smarthouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./smarthouse
    container_name: django-smarthouse
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smarthouse
    volumes:
      - ./smarthouse:/code
    depends_on:
      - db

volumes:
  postgres_data:
